### PR TITLE
feat: allow usb connections via auto-detection

### LINKED ISSUE #6: USB support
Hi,
When trying to search for a printer and choose the usb port as the communication port, an error appear in the library saying the device is not supported (js error), does this package support usb connection? If so can you attached an example? If not there is any attention to do so?

 Thanks in advance for this great package

### PR DESCRIPTION
**Pull request by vicary**
Fixes #6

@HatalDev Not sure if emulators can proxy through USB connections, but we are good with emulator tests without actual devices if USB works.

You may run the example app for test prints using the commands below, it would be really kind of you to also attach photos for test prints!

## Installation

```bash
yarn

cd examples/PrinterTestApp

# Start metro server
yarn start
```

## Android

```bash
# Test Android old arch
yarn and:old

# Clear previous builds to change arch
yarn and:clean

# Test Android new arch
yarn and:new
```

## iOS

```bash
# Test iOS old arch
yarn ios:old

# Clear previous builds to change arch
yarn ios:clean

# Test iOS new arch
yarn ios:new
```

### CODE REVIEW

**Comment by HatalDev** [comment]
@vicary can you upgrade the Gradle to the latest version? 
beside that there is any way to install the package with your latest changes to existing project using yarn/npm?

**Comment by vicary** [comment]
Usually you don't need to upgrade the gradle version of the plugin, for the example app you may simply edit the line below to your desired version and rebuild.
https://github.com/vicary/react-native-citizen-escposprinter/blob/6318b887b07d7102bcd415d5f4e08fade63cb08c/examples/PrinterTestApp/android/gradle/wrapper/gradle-wrapper.properties#L3

The example app has workspace deps, it's the best way to install without publishing. You may try installing the locally built plugin via `yarn link` or `npm link`, but you are likely to hit an error saying that the linked version of `react` and `react-native` being different with those in your app. It's really a rabbit hole to dedupe symlink dependencies so I don't recommend this unless you do this a lot.

**Comment by HatalDev** [comment]
@vicary Hi, when I run yarn and:old the application works but when I press search printers, I get an error "Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference" (both on simulator and on physical device, connected to the printer). when running yarn and:new the build fails and I get an error 
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-citizen-escposprinter:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
``` 
and also 
```
2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)
```

**Comment by vicary** [comment]
@HatalDev USB shouldn't need to use the search function, you may have to change the code a bit and call `connect()` with the USB constant directly.

I'll take a look at the function bindings in the mean time, there maybe a mismatched argument type on the native layer.

**Comment by HatalDev** [comment]
@vicary I tried setting just one Pressable to use the `connect` function. 
```
<Pressable
  className="bg-gray-200 active:bg-gray-300 active:opacity-50 rounded-xl"
  onPress={async () => {
    try {
      await connect(ESCPOSConst.CMP_PORT_USB);
    } catch (err) { }
  }}>
</Pressable>
```

I get an error 
`Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter address`

When I try to provide a string as an address, I get an error saying it's not supported for USB connection.

**Comment by vicary** [comment]
@HatalDev that is really weird, using an uninstantiated `null` variable of UsbDevice as the second parameter is a direct copy from the SDK docs.

I'll try experimenting a bit more, please do let me know if you see that I am doing it wrong here

https://github.com/vicary/react-native-citizen-escposprinter/blob/53190e3e307ec5fe0f11598702f0fc24049be023/packages/react-native-citizen-escposprinter/android/src/main/java/com/citizenescposprinter/CitizenEscposprinterModule.kt#L83

**Comment by vicary** [comment]
I can build both archs after fixing the optional parameter binding, I cannot reproduce the error when running printer search though.

A new button is added to the example app for easier USB tests.

https://github.com/user-attachments/assets/d157edaf-e34b-460b-9d02-0438e62f45f9

**Comment by HatalDev** [comment]
@vicary I've downloaded the latest version, when trying to build I'm getting the following error 
`Execution failed for task ':react-native-citizen-escposprinter:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction`

it's because of the `connect` function in the `CitizenEscposprinterModule.kt` file, when removing the question mark from the address string, the app builds, and when clicking on connect printer the same error of 
`Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter address`
is still happening

**Comment by vicary** [comment]
@HatalDev I should also update `CitizenEscposprinterSpec.kt` to match the function signature, pushed again to allow `null` addresses for USB.

**Comment by HatalDev** [comment]
@vicary I'm very happy to confirm that the usb printing is working perfectly now, do you need any further help in order to publish it to the main branch, and update the npm package?

**Comment by vicary** [comment]
A verbal confirmation that you have tested all 4 environments would be enough, I would otherwise document the untested items. Then we are good to go!

**Comment by HatalDev** [comment]
@vicary I can confirm that both environments of android are working, currently I can't verify it on iOS, but I believe I could do this in couple of days, maybe we can continue with the android for now, as it working exactly as it should.

**Comment by vicary** [comment]
I'll add a temporary warning section in the README and release it tomorrow.

You may continue commenting in this PR, I'll remove the section if it turns out working!

**Pull request merged**
