### PR TITLE
feat: Upgrade SDK V212E

### PR DESCRIPTION
**Pull request by vicary**
Exposing new properties and methods added in the new versions.

1. [x] printerCheckEx (iOS)
2. [x] openDrawerEx (iOS)
3. [x] PageModeArea property
4. [x] PageModePrinteArea property
5. [x] PageModePrintDirection property
6. [x] PageModeHorizontalPosition property
7. [x] PageModeVerticalPosition property
8. [x] RecLineSpacing property
9. [x] MapMode property

Checklist:

1. Upgrade RN to 0.75
   1. [x] Reinitialize example app in Expo because upgrading RN is a pain
1. Test Android builds
   1. [x] oldarch
   1. [x] newarch
1. Test iOS builds
   1. [x] oldarch
   1. [x] newarch

## Note for future me

The error `... RCTEvents.receiveEvent() of undefined. Module has not been registered as a callable ...` is specifically triggered by `expo-router` and in turn `react-native-screens` over the bridgeless mode enforced by expo when New Architecture is enabled.

This only happens when `index.tsx` is used at `app/` root in iOS.

### CODE REVIEW

**Comment by HatalDev** [comment]
@vicary hi, i run my app after more than a month and the usb connection isn't working anymore, even tough my code haven't changed, i tried to run your example app on my other computer(the one i did the test for the project) and it also not working, however when i download this branch with the updated SDK it's working flawless, do you have any idea why it's happening ? and when you will release this sdk update to the main branch?

**Comment by vicary** [comment]
@HatalDev It sounds like some kind of minor version upgrade is breaking it, stale `node_modules`, or build caches.

On the other hand, the only thing stopping this branch is the way that `expo-router` treats `index.ts` is breaking this version of example app. If you are sure this branch is working for you, we can publish this branch very soon.

**Comment by HatalDev** [comment]
@vicary i've tried your solution with the node_modules and completly clean the build caches and still not working with the "Failed connection to the printer", only the new branch is working for me now.
When can you release it?

**Comment by vicary** [comment]
@HatalDev It's released, please give `0.4.0` a test. I'll add the caveat to README later.

**Pull request merged**
